
all: p1 p2 p3 p4 pipe

clean:
	rm -f p1 p2 p3 p4 p4.out pipe

p1: p1.c
	gcc -g -Wall -o p1 p1.c

p2: p2.c
	gcc -g -Wall -o p2 p2.c

p3: p3.c
	gcc -g -Wall -o p3 p3.c

p4: p4.c
	gcc -g -Wall -o p4 p4.c

pipe: pipe.c
	gcc -g -Wall -o pipe pipe.c
